#!/bin/bash

configdir="/pia"
tokenfile="$configdir/.token"
pf_persistfile="$configdir/portsig.json"

sharedir="/pia-shared"
portfile="$sharedir/port.dat"

pia_cacrt="/rsa_4096.crt"
wg_conf="/etc/wireguard/wg0.conf"

# Handle shutdown behavior
finish () {
  [ $PORT_FORWARDING -eq 1 ] && pkill -f 'pf.sh'
  echo "$(date): Shutting down WireGuard"
  [ -w "$portfile" ] && rm "$portfile"
  if [ $WG_USERSPACE -eq 1 ]; then
    WG_QUICK_USERSPACE_IMPLEMENTATION=wireguard-go wg-quick down wg0
  else
    wg-quick down wg0
  fi
  exit 0
}

trap finish SIGTERM SIGINT SIGQUIT

# All done. Sleep and wait for termination.
now_sleep () {
  sleep infinity &
  wait $!
}

# An error with no recovery logic occured. Either go to sleep or exit.
fatal_error () {
  echo "$(date): Fatal error"
  [ $EXIT_ON_FATAL -eq 1 ] && exit 1
  sleep infinity &
  wait $!
}

# Get a new auth token
# Unsure how long an auth token will remain valid
get_auth_token () {
  [ -z "$PASS" ] && echo "$(date): PIA password not set. Unable to retrieve new auth token." && fatal_error
  [ -z "$USER" ] && echo "$(date): PIA username not set. Unable to retrieve new auth token." && fatal_error
  echo "$(date): Generating auth token"
  /scripts/pia-auth.sh -u "$USER" -p "$PASS" > "$tokenfile"
  [ $? -ne 0 ] && echo "$(date): Failed to acquire new auth token" && fatal_error
  chmod 600 "$tokenfile"
}

[ -w "$portfile" ] && rm "$portfile"

# No LOC supplied
[ -z "$LOC" ] && /scripts/wg-gen.sh -a && fatal_error

[ ! -r "$tokenfile" ] && get_auth_token

# Generate wg0.conf
/scripts/wg-gen.sh -l "$LOC" -t "$tokenfile" -o "$wg_conf" -k "/RegionsListPubKey.pem" -d "$VPNDNS"
result=$?
if [ "$result" -eq 2 ]; then
  # Reauth and retry if auth failed
  get_auth_token
  /scripts/wg-gen.sh -l "$LOC" -t "$tokenfile" -o "$wg_conf" -k "/RegionsListPubKey.pem" -d "$VPNDNS" || fatal_error
elif [ "$result" -eq 3 ]; then
  # Location not found
  echo "$(date): Location $LOC not found"
  /scripts/wg-gen.sh -a
  fatal_error
elif [ "$result" -ne 0 ]; then
  echo "$(date): Failed to generate WireGuard config"
  fatal_error
fi

# Add PersistentKeepalive if KEEPALIVE is set
[ $KEEPALIVE -gt 0 ] && echo "PersistentKeepalive = $KEEPALIVE" >> "$wg_conf"

# Bring up Wireguard interface
echo "$(date): Bringing up WireGuard interface wg0"
wg-quick up wg0 || fatal_error

# Print out wg interface info
echo
wg
echo

echo "$(date): WireGuard successfully started"

# Setup port forwarding if requested and available
pf_api_ip=$(grep '#pf api' "$wg_conf"| sed 's/#pf api ip: \(.*\)/\1/')
pf_cn=$(grep '#cn: ' "$wg_conf"| sed 's/#cn: \(.*\)/\1/')
if [ $PORT_FORWARDING -eq 1 ] && [ -n "$pf_api_ip" ]; then
  echo "$(date): Starting port forward script"
  /scripts/pf.sh -t "$tokenfile" -i "$pf_api_ip" -n "$pf_cn" -p "$portfile" -c "$pia_cacrt" -s "/scripts/pf_success.sh" -r "$pf_persistfile" &
fi

now_sleep
